// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  // apiUrl: 'https://7zlzt08oi1.execute-api.us-east-1.amazonaws.com', // 
  apiUrl: 'https://api.cashier2go.com', // 'https://31m1uop4pi.execute-api.us-east-1.amazonaws.com/dev', //'http://localhost:3000'
  bucket: 'https://octagt-erp.s3.amazonaws.com/',
  currencies: [
    {"c":"AED","n":"\u062f.\u0625;","name":"UAE dirham"},
    {"c":"AFN","n":"Afs","name":"Afghan afghani"},
    {"c":"ALL","n":"L","name":"Albanian lek"},
    {"c":"AMD","n":"AMD","name":"Armenian dram"},
    {"c":"ANG","n":"NA\u0192","name":"Netherlands Antillean gulden"},
    {"c":"AOA","n":"Kz","name":"Angolan kwanza"},
    {"c":"ARS","n":"$","name":"Argentine peso"},
    {"c":"AUD","n":"$","name":"Australian dollar"},
    {"c":"AWG","n":"\u0192","name":"Aruban florin"},
    {"c":"AZN","n":"AZN","name":"Azerbaijani manat"},
    {"c":"BAM","n":"KM","name":"Bosnia and Herzegovina konvertibilna marka"},
    {"c":"BBD","n":"Bds$","name":"Barbadian dollar"},
    {"c":"BDT","n":"\u09f3","name":"Bangladeshi taka"},
    {"c":"BGN","n":"BGN","name":"Bulgarian lev"},
    {"c":"BHD","n":".\u062f.\u0628","name":"Bahraini dinar"},
    {"c":"BIF","n":"FBu","name":"Burundi franc"},
    {"c":"BMD","n":"BD$","name":"Bermudian dollar"},
    {"c":"BND","n":"B$","name":"Brunei dollar"},
    {"c":"BOB","n":"Bs.","name":"Bolivian boliviano"},
    {"c":"BRL","n":"R$","name":"Brazilian real"},
    {"c":"BSD","n":"B$","name":"Bahamian dollar"},
    {"c":"BTN","n":"Nu.","name":"Bhutanese ngultrum"},
    {"c":"BWP","n":"P","name":"Botswana pula"},
    {"c":"BYR","n":"Br","name":"Belarusian ruble"},
    {"c":"BZD","n":"BZ$","name":"Belize dollar"},
    {"c":"CAD","n":"$","name":"Canadian dollar"},
    {"c":"CDF","n":"F","name":"Congolese franc"},
    {"c":"CHF","n":"Fr.","name":"Swiss franc"},
    {"c":"CLP","n":"$","name":"Chilean peso"},
    {"c":"CNY","n":"\u00a5","name":"Chinese/Yuan renminbi"},
    {"c":"COP","n":"Col$","name":"Colombian peso"},
    {"c":"CRC","n":"\u20a1","name":"Costa Rican colon"},
    {"c":"CUC","n":"$","name":"Cuban peso"},
    {"c":"CVE","n":"Esc","name":"Cape Verdean escudo"},
    {"c":"CZK","n":"K\u010d","name":"Czech koruna"},
    {"c":"DJF","n":"Fdj","name":"Djiboutian franc"},
    {"c":"DKK","n":"Kr","name":"Danish krone"},
    {"c":"DOP","n":"RD$","name":"Dominican peso"},
    {"c":"DZD","n":"\u062f.\u062c","name":"Algerian dinar"},
    {"c":"EEK","n":"KR","name":"Estonian kroon"},
    {"c":"EGP","n":"\u00a3","name":"Egyptian pound"},
    {"c":"ERN","n":"Nfa","name":"Eritrean nakfa"},
    {"c":"ETB","n":"Br","name":"Ethiopian birr"},
    {"c":"EUR","n":"\u20ac","name":"European Euro"},
    {"c":"FJD","n":"FJ$","name":"Fijian dollar"},
    {"c":"FKP","n":"\u00a3","name":"Falkland Islands pound"},
    {"c":"GBP","n":"\u00a3","name":"British pound"},
    {"c":"GEL","n":"GEL","name":"Georgian lari"},
    {"c":"GHS","n":"GH\u20b5","name":"Ghanaian cedi"},
    {"c":"GIP","n":"\u00a3","name":"Gibraltar pound"},
    {"c":"GMD","n":"D","name":"Gambian dalasi"},
    {"c":"GNF","n":"FG","name":"Guinean franc"},
    {"c":"GQE","n":"CFA","name":"Central African CFA franc"},
    {"c":"GTQ","n":"Q","name":"Guatemalan quetzal"},
    {"c":"GYD","n":"GY$","name":"Guyanese dollar"},
    {"c":"HKD","n":"HK$","name":"Hong Kong dollar"},
    {"c":"HNL","n":"L","name":"Honduran lempira"},
    {"c":"HRK","n":"kn","name":"Croatian kuna"},
    {"c":"HTG","n":"G","name":"Haitian gourde"},
    {"c":"HUF","n":"Ft","name":"Hungarian forint"},
    {"c":"IDR","n":"Rp","name":"Indonesian rupiah"},
    {"c":"ILS","n":"\u20aa","name":"Israeli new sheqel"},
    {"c":"INR","n":"\u20B9","name":"Indian rupee"},
    {"c":"IQD","n":"\u062f.\u0639","name":"Iraqi dinar"},
    {"c":"IRR","n":"IRR","name":"Iranian rial"},
    {"c":"ISK","n":"kr","name":"Icelandic kr\u00f3na"},
    {"c":"JMD","n":"J$","name":"Jamaican dollar"},
    {"c":"JOD","n":"JOD","name":"Jordanian dinar"},
    {"c":"JPY","n":"\u00a5","name":"Japanese yen"},
    {"c":"KES","n":"KSh","name":"Kenyan shilling"},
    {"c":"KGS","n":"\u0441\u043e\u043c","name":"Kyrgyzstani som"},
    {"c":"KHR","n":"\u17db","name":"Cambodian riel"},
    {"c":"KMF","n":"KMF","name":"Comorian franc"},
    {"c":"KPW","n":"W","name":"North Korean won"},
    {"c":"KRW","n":"W","name":"South Korean won"},
    {"c":"KWD","n":"KWD","name":"Kuwaiti dinar"},
    {"c":"KYD","n":"KY$","name":"Cayman Islands dollar"},
    {"c":"KZT","n":"T","name":"Kazakhstani tenge"},
    {"c":"LAK","n":"KN","name":"Lao kip"},
    {"c":"LBP","n":"\u00a3","name":"Lebanese lira"},
    {"c":"LKR","n":"Rs","name":"Sri Lankan rupee"},
    {"c":"LRD","n":"L$","name":"Liberian dollar"},
    {"c":"LSL","n":"M","name":"Lesotho loti"},
    {"c":"LTL","n":"Lt","name":"Lithuanian litas"},
    {"c":"LVL","n":"Ls","name":"Latvian lats"},
    {"c":"LYD","n":"LD","name":"Libyan dinar"},
    {"c":"MAD","n":"MAD","name":"Moroccan dirham"},
    {"c":"MDL","n":"MDL","name":"Moldovan leu"},
    {"c":"MGA","n":"FMG","name":"Malagasy ariary"},
    {"c":"MKD","n":"MKD","name":"Macedonian denar"},
    {"c":"MMK","n":"K","name":"Myanma kyat"},
    {"c":"MNT","n":"\u20ae","name":"Mongolian tugrik"},
    {"c":"MOP","n":"P","name":"Macanese pataca"},
    {"c":"MRO","n":"UM","name":"Mauritanian ouguiya"},
    {"c":"MUR","n":"Rs","name":"Mauritian rupee"},
    {"c":"MVR","n":"Rf","name":"Maldivian rufiyaa"},
    {"c":"MWK","n":"MK","name":"Malawian kwacha"},
    {"c":"MXN","n":"$","name":"Mexican peso"},
    {"c":"MYR","n":"RM","name":"Malaysian ringgit"},
    {"c":"MZM","n":"MTn","name":"Mozambican metical"},
    {"c":"NAD","n":"N$","name":"Namibian dollar"},
    {"c":"NGN","n":"\u20a6","name":"Nigerian naira"},
    {"c":"NIO","n":"C$","name":"Nicaraguan c\u00f3rdoba"},
    {"c":"NOK","n":"kr","name":"Norwegian krone"},
    {"c":"NPR","n":"NRs","name":"Nepalese rupee"},
    {"c":"NZD","n":"NZ$","name":"New Zealand dollar"},
    {"c":"OMR","n":"OMR","name":"Omani rial"},
    {"c":"PAB","n":"B./","name":"Panamanian balboa"},
    {"c":"PEN","n":"S/.","name":"Peruvian nuevo sol"},
    {"c":"PGK","n":"K","name":"Papua New Guinean kina"},
    {"c":"PHP","n":"\u20b1","name":"Philippine peso"},
    {"c":"PKR","n":"Rs.","name":"Pakistani rupee"},
    {"c":"PLN","n":"z\u0142","name":"Polish zloty"},
    {"c":"PYG","n":"\u20b2","name":"Paraguayan guarani"},
    {"c":"QAR","n":"QR","name":"Qatari riyal"},
    {"c":"RON","n":"L","name":"Romanian leu"},
    {"c":"RSD","n":"din.","name":"Serbian dinar"},
    {"c":"RUB","n":"R","name":"Russian ruble"},
    {"c":"SAR","n":"SR","name":"Saudi riyal"},
    {"c":"SBD","n":"SI$","name":"Solomon Islands dollar"},
    {"c":"SCR","n":"SR","name":"Seychellois rupee"},
    {"c":"SDG","n":"SDG","name":"Sudanese pound"},
    {"c":"SEK","n":"kr","name":"Swedish krona"},
    {"c":"SGD","n":"S$","name":"Singapore dollar"},
    {"c":"SHP","n":"\u00a3","name":"Saint Helena pound"},
    {"c":"SLL","n":"Le","name":"Sierra Leonean leone"},
    {"c":"SOS","n":"Sh.","name":"Somali shilling"},
    {"c":"SRD","n":"$","name":"Surinamese dollar"},
    {"c":"SYP","n":"LS","name":"Syrian pound"},
    {"c":"SZL","n":"E","name":"Swazi lilangeni"},
    {"c":"THB","n":"\u0e3f","name":"Thai baht"},
    {"c":"TJS","n":"TJS","name":"Tajikistani somoni"},
    {"c":"TMT","n":"m","name":"Turkmen manat"},
    {"c":"TND","n":"DT","name":"Tunisian dinar"},
    {"c":"TRY","n":"TRY","name":"Turkish new lira"},
    {"c":"TTD","n":"TT$","name":"Trinidad and Tobago dollar"},
    {"c":"TWD","n":"NT$","name":"New Taiwan dollar"},
    {"c":"TZS","n":"TZS","name":"Tanzanian shilling"},
    {"c":"UAH","n":"UAH","name":"Ukrainian hryvnia"},
    {"c":"UGX","n":"USh","name":"Ugandan shilling"},
    {"c":"USD","n":"US$","name":"United States dollar"},
    {"c":"UYU","n":"$U","name":"Uruguayan peso"},
    {"c":"UZS","n":"UZS","name":"Uzbekistani som"},
    {"c":"VEB","n":"Bs","name":"Venezuelan bolivar"},
    {"c":"VND","n":"\u20ab","name":"Vietnamese dong"},
    {"c":"VUV","n":"VT","name":"Vanuatu vatu"},
    {"c":"WST","n":"WS$","name":"Samoan tala"},
    {"c":"XAF","n":"CFA","name":"Central African CFA franc"},
    {"c":"XCD","n":"EC$","name":"East Caribbean dollar"},
    {"c":"XDR","n":"SDR","name":"Special Drawing Rights"},
    {"c":"XOF","n":"CFA","name":"West African CFA franc"},
    {"c":"XPF","n":"F","name":"CFP franc"},
    {"c":"YER","n":"YER","name":"Yemeni rial"},
    {"c":"ZAR","n":"R","name":"South African rand"},
    {"c":"ZMK","n":"ZK","name":"Zambian kwacha"},
    {"c":"ZWR","n":"Z$","name":"Zimbabwean dollar"}
  ],
  countries: [{"n":"Afghanistan","c":"AFA"},{"n":"Åland Islands","c":"ALA"},{"n":"Albania","c":"ALB"},{"n":"Algeria","c":"DZA"},{"n":"American Samoa","c":"ASM"},{"n":"Andorra","c":"AND"},{"n":"Angola","c":"AGO"},{"n":"Anguilla","c":"AIA"},{"n":"Antarctica","c":"ATA"},{"n":"Antigua and Barbuda","c":"ATG"},{"n":"Argentina","c":"ARG"},{"n":"Armenia","c":"ARM"},{"n":"Aruba","c":"ABW"},{"n":"Australia","c":"AUS"},{"n":"Austria","c":"AUT"},{"n":"Azerbaijan","c":"AZE"},{"n":"Bahamas","c":"BHS"},{"n":"Bahrain","c":"BHR"},{"n":"Bangladesh","c":"BGD"},{"n":"Barbados","c":"BRB"},{"n":"Belarus","c":"BLR"},{"n":"Belgium","c":"BEL"},{"n":"Belize","c":"BLZ"},{"n":"Benin","c":"BEN"},{"n":"Bermuda","c":"BMU"},{"n":"Bhutan","c":"BTN"},{"n":"Bolivia (Plurinational State of)","c":"BOL"},{"n":"Bonaire, Sint Eustatius and Saba","c":"BES"},{"n":"Bosnia and Herzegovina","c":"BIH"},{"n":"Botswana","c":"BWA"},{"n":"Bouvet Island","c":"BVT"},{"n":"Brazil","c":"BRA"},{"n":"British Indian Ocean Territory","c":"IOT"},{"n":"Brunei Darussalam","c":"BRN"},{"n":"Bulgaria","c":"BGR"},{"n":"Burkina Faso","c":"BFA"},{"n":"Burundi","c":"BDI"},{"n":"Cabo Verde","c":"CPV"},{"n":"Cambodia","c":"KHM"},{"n":"Cameroon","c":"CMR"},{"n":"Canada","c":"CAN"},{"n":"Cayman Islands","c":"CYM"},{"n":"Central African Republic","c":"CAF"},{"n":"Chad","c":"TCD"},{"n":"Chile","c":"CHL"},{"n":"China","c":"CHN"},{"n":"Christmas Island","c":"CXR"},{"n":"Cocos (Keeling) Islands","c":"CCK"},{"n":"Colombia","c":"COL"},{"n":"Comoros","c":"COM"},{"n":"Congo","c":"COG"},{"n":"Congo, Democratic Republic of the","c":"COD"},{"n":"Cook Islands","c":"COK"},{"n":"Costa Rica","c":"CRI"},{"n":"Côte d'Ivoire","c":"CIV"},{"n":"Croatia","c":"HRV"},{"n":"Cuba","c":"CUB"},{"n":"Curaçao","c":"CUW"},{"n":"Cyprus","c":"CYP"},{"n":"Czechia","c":"CZE"},{"n":"Denmark","c":"DNK"},{"n":"Djibouti","c":"DJI"},{"n":"Dominica","c":"DMA"},{"n":"Dominican Republic","c":"DOM"},{"n":"Ecuador","c":"ECU"},{"n":"Egypt","c":"EGY"},{"n":"El Salvador","c":"SLV"},{"n":"Equatorial Guinea","c":"GNQ"},{"n":"Eritrea","c":"ERI"},{"n":"Estonia","c":"EST"},{"n":"Eswatini","c":"SWZ"},{"n":"Ethiopia","c":"ETH"},{"n":"Falkland Islands (Malvinas)","c":"FLK"},{"n":"Faroe Islands","c":"FRO"},{"n":"Fiji","c":"FJI"},{"n":"Finland","c":"FIN"},{"n":"France","c":"FRA"},{"n":"French Guiana","c":"GUF"},{"n":"French Polynesia","c":"PYF"},{"n":"French Southern Territories","c":"ATF"},{"n":"Gabon","c":"GAB"},{"n":"Gambia","c":"GMB"},{"n":"Georgia","c":"GEO"},{"n":"Germany","c":"DEU"},{"n":"Ghana","c":"GHA"},{"n":"Gibraltar","c":"GIB"},{"n":"Greece","c":"GRC"},{"n":"Greenland","c":"GRL"},{"n":"Grenada","c":"GRD"},{"n":"Guadeloupe","c":"GLP"},{"n":"Guam","c":"GUM"},{"n":"Guatemala","c":"GTM"},{"n":"Guernsey","c":"GGY"},{"n":"Guinea","c":"GIN"},{"n":"Guinea-Bissau","c":"GNB"},{"n":"Guyana","c":"GUY"},{"n":"Haiti","c":"HTI"},{"n":"Heard Island and McDonald Islands","c":"HMD"},{"n":"Holy See","c":"VAT"},{"n":"Honduras","c":"HND"},{"n":"Hong Kong","c":"HKG"},{"n":"Hungary","c":"HUN"},{"n":"Iceland","c":"ISL"},{"n":"India","c":"IND"},{"n":"Indonesia","c":"IDN"},{"n":"Iran (Islamic Republic of)","c":"IRN"},{"n":"Iraq","c":"IRQ"},{"n":"Ireland","c":"IRL"},{"n":"Isle of Man","c":"IMN"},{"n":"Israel","c":"ISR"},{"n":"Italy","c":"ITA"},{"n":"Jamaica","c":"JAM"},{"n":"Japan","c":"JPN"},{"n":"Jersey","c":"JEY"},{"n":"Jordan","c":"JOR"},{"n":"Kazakhstan","c":"KAZ"},{"n":"Kenya","c":"KEN"},{"n":"Kiribati","c":"KIR"},{"n":"Korea (Democratic People's Republic of)","c":"PRK"},{"n":"Korea, Republic of","c":"KOR"},{"n":"Kuwait","c":"KWT"},{"n":"Kyrgyzstan","c":"KGZ"},{"n":"Lao People's Democratic Republic","c":"LAO"},{"n":"Latvia","c":"LVA"},{"n":"Lebanon","c":"LBN"},{"n":"Lesotho","c":"LSO"},{"n":"Liberia","c":"LBR"},{"n":"Libya","c":"LBY"},{"n":"Liechtenstein","c":"LIE"},{"n":"Lithuania","c":"LTU"},{"n":"Luxembourg","c":"LUX"},{"n":"Macao","c":"MAC"},{"n":"Madagascar","c":"MDG"},{"n":"Malawi","c":"MWI"},{"n":"Malaysia","c":"MYS"},{"n":"Maldives","c":"MDV"},{"n":"Mali","c":"MLI"},{"n":"Malta","c":"MLT"},{"n":"Marshall Islands","c":"MHL"},{"n":"Martinique","c":"MTQ"},{"n":"Mauritania","c":"MRT"},{"n":"Mauritius","c":"MUS"},{"n":"Mayotte","c":"MYT"},{"n":"Mexico","c":"MEX"},{"n":"Micronesia (Federated States of)","c":"FSM"},{"n":"Moldova, Republic of","c":"MDA"},{"n":"Monaco","c":"MCO"},{"n":"Mongolia","c":"MNG"},{"n":"Montenegro","c":"MNE"},{"n":"Montserrat","c":"MSR"},{"n":"Morocco","c":"MAR"},{"n":"Mozambique","c":"MOZ"},{"n":"Myanmar","c":"MMR"},{"n":"Namibia","c":"NAM"},{"n":"Nauru","c":"NRU"},{"n":"Nepal","c":"NPL"},{"n":"Netherlands","c":"NLD"},{"n":"New Caledonia","c":"NCL"},{"n":"New Zealand","c":"NZL"},{"n":"Nicaragua","c":"NIC"},{"n":"Niger","c":"NER"},{"n":"Nigeria","c":"NGA"},{"n":"Niue","c":"NIU"},{"n":"Norfolk Island","c":"NFK"},{"n":"North Macedonia","c":"MKD"},{"n":"Northern Mariana Islands","c":"MNP"},{"n":"Norway","c":"NOR"},{"n":"Oman","c":"OMN"},{"n":"Pakistan","c":"PAK"},{"n":"Palau","c":"PLW"},{"n":"Palestine, State of","c":"PSE"},{"n":"Panama","c":"PAN"},{"n":"Papua New Guinea","c":"PNG"},{"n":"Paraguay","c":"PRY"},{"n":"Peru","c":"PER"},{"n":"Philippines","c":"PHL"},{"n":"Pitcairn","c":"PCN"},{"n":"Poland","c":"POL"},{"n":"Portugal","c":"PRT"},{"n":"Puerto Rico","c":"PRI"},{"n":"Qatar","c":"QAT"},{"n":"Réunion","c":"REU"},{"n":"Romania","c":"ROU"},{"n":"Russian Federation","c":"RUS"},{"n":"Rwanda","c":"RWA"},{"n":"Saint Barthélemy","c":"BLM"},{"n":"Saint Helena, Ascension and Tristan da Cunha","c":"SHN"},{"n":"Saint Kitts and Nevis","c":"KNA"},{"n":"Saint Lucia","c":"LCA"},{"n":"Saint Martin (French part)","c":"MAF"},{"n":"Saint Pierre and Miquelon","c":"SPM"},{"n":"Saint Vincent and the Grenadines","c":"VCT"},{"n":"Samoa","c":"WSM"},{"n":"San Marino","c":"SMR"},{"n":"Sao Tome and Principe","c":"STP"},{"n":"Saudi Arabia","c":"SAU"},{"n":"Senegal","c":"SEN"},{"n":"Serbia","c":"SRB"},{"n":"Seychelles","c":"SYC"},{"n":"Sierra Leone","c":"SLE"},{"n":"Singapore","c":"SGP"},{"n":"Sint Maarten (Dutch part)","c":"SXM"},{"n":"Slovakia","c":"SVK"},{"n":"Slovenia","c":"SVN"},{"n":"Solomon Islands","c":"SLB"},{"n":"Somalia","c":"SOM"},{"n":"South Africa","c":"ZAF"},{"n":"South Georgia and the South Sandwich Islands","c":"SGS"},{"n":"South Sudan","c":"SSD"},{"n":"Spain","c":"ESP"},{"n":"Sri Lanka","c":"LKA"},{"n":"Sudan","c":"SDN"},{"n":"Surin","c":"SUR"},{"n":"Svalbard and Jan Mayen","c":"SJM"},{"n":"Sweden","c":"SWE"},{"n":"Switzerland","c":"CHE"},{"n":"Syrian Arab Republic","c":"SYR"},{"n":"Taiwan, Province of China","c":"TWN"},{"n":"Tajikistan","c":"TJK"},{"n":"Tanzania, United Republic of","c":"TZA"},{"n":"Thailand","c":"THA"},{"n":"Timor-Leste","c":"TLS"},{"n":"Togo","c":"TGO"},{"n":"Tokelau","c":"TKL"},{"n":"Tonga","c":"TON"},{"n":"Trinidad and Tobago","c":"TTO"},{"n":"Tunisia","c":"TUN"},{"n":"Turkey","c":"TUR"},{"n":"Turkmenistan","c":"TKM"},{"n":"Turks and Caicos Islands","c":"TCA"},{"n":"Tuvalu","c":"TUV"},{"n":"Uganda","c":"UGA"},{"n":"Ukraine","c":"UKR"},{"n":"United Arab Emirates","c":"ARE"},{"n":"United Kingdom of Great Britain and Northern Ireland","c":"GBR"},{"n":"United States of America","c":"USA"},{"n":"United States Minor Outlying Islands","c":"UMI"},{"n":"Uruguay","c":"URY"},{"n":"Uzbekistan","c":"UZB"},{"n":"Vanuatu","c":"VUT"},{"n":"Venezuela (Bolivarian Republic of)","c":"VEN"},{"n":"Viet Nam","c":"VNM"},{"n":"Virgin Islands (British)","c":"VGB"},{"n":"Virgin Islands (U.S.)","c":"VIR"},{"n":"Wallis and Futuna","c":"WLF"},{"n":"Western Sahara","c":"ESH"},{"n":"Yemen","c":"YEM"},{"n":"Zambia","c":"ZMB"},{"n":"Zimbabwe","c":"ZWE"}]
  // apiLocUrl: '7ea1cff846ab05c3a53b2471383af0f1'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
